# This module contains how much each item changes throughout the sell in period.
GENERAL_ITEM_DELTA = -1
GENERAL_ITEM_DELTA_AFTER_SELL_IN = -2
AGED_BRIE_DELTA = 1
AGED_BRIE_DELTA_AFTER_SELL_IN = 2
BACKSTAGE_PASSES_DELTA_BEFORE_DAY_10 = 1
BACKSTAGE_PASSES_DELTA_BEFORE_DAY_5 = 2
BACKSTAGE_PASSES_DELTA_BEFORE_DAY_0 = 3
BACKSTAGE_PASSES_DELTA_AFTER_SELL_IN = -50
CONJURED_DELTA = -2
CONJURED_DELTA_AFTER_SELL_IN = -4
MAX_QUALITY = 50
MIN_QUALITY = 0
